table dim_location
	lineageTag: 7ebae9b3-a33d-470c-a8f8-fc1ed80d4262

	column location_ID
		dataType: int64
		formatString: 0
		lineageTag: f6fdfb20-db22-481d-b4c4-cbe5e06c6efe
		summarizeBy: none
		sourceColumn: location_ID

		annotation SummarizationSetBy = Automatic

	column municipality_name
		dataType: string
		lineageTag: 69b487a9-1cd2-49df-a05c-41891d23a17b
		dataCategory: City
		summarizeBy: none
		sourceColumn: municipality_name

		annotation SummarizationSetBy = Automatic

	column municipality_code
		dataType: string
		lineageTag: 39c59694-b3cc-44b5-b14a-280d197f1f46
		summarizeBy: none
		sourceColumn: municipality_code

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: caf35c51-a399-41ac-a72c-5f8593637e3e
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: region_name

		annotation SummarizationSetBy = Automatic

	column 'Map Location' = 'dim_location'[municipality_name] & ", Sweden"
		lineageTag: 7fbdfea3-4249-4daf-931c-ba9d70e63529
		dataCategory: City
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: 0f84f11d-01ac-4dee-9dff-91c42d2e0d18
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	partition dim_location = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-7405617439098346.6.azuredatabricks.net", "/sql/1.0/warehouses/5bf990c8cb05ff5c", [Catalog="labour_market_platform", Database="gold_analysis", QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    dim_location_gold_analysis_labour_market_platform = Source{[Item="dim_location",Schema="gold_analysis",Catalog="labour_market_platform"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dim_location_gold_analysis_labour_market_platform,"ALLA","",Replacer.ReplaceText,{"municipality_code"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "country_code", each "SE")
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

